### ISSUE TITLE
[FEATURE] SSH handler should raise an error, if unable to connect

### ISSUE THREAD

**Issue by MichaelSasser** [MichaelSasser/matrixctl#7]
**Describe the solution you'd like**
See title.

**Additional context**

```console
matrixctl -d update
2020-04-30 07:25:58 - DEBUG - args=Namespace(debug=True, func=<function update at 0x7fa3871b2700>)
2020-04-30 07:25:58 - DEBUG - Disabing help on AttributeError
2020-04-30 07:25:58 - WARNING - In debugging mode help is disabled! If you don't use any attibutes, the program will throw a AttributeError like: "AttributeError: 'Namespace' object has no attribute 'func".' This is perfectly normal and not a bug. If you want the help in debug mode, use the "--help" attribute.
2020-04-30 07:25:58 - DEBUG - Loading Config file(s)
2020-04-30 07:25:58 - DEBUG - [SYNAPSE]
2020-04-30 07:25:58 - DEBUG -   ├─  Path := /home/michael/repos/playbooks/synapse/matrix-docker-ansible-deploy
2020-04-30 07:25:58 - DEBUG -   ┴
2020-04-30 07:25:58 - DEBUG - [ANSIBLE]
2020-04-30 07:25:58 - DEBUG -   ├─  Path := /home/michael/repos/playbooks/matrix
2020-04-30 07:25:58 - DEBUG -   ├─  Cfg := /home/michael/repos/playbooks/matrix/ansible.cfg
2020-04-30 07:25:58 - DEBUG -   ├─  Playbook :=  setup.yml
2020-04-30 07:25:58 - DEBUG -   ├─  DeployTags := ['setup-all']
2020-04-30 07:25:58 - DEBUG -   ┴
2020-04-30 07:25:58 - DEBUG - [API]
2020-04-30 07:25:58 - DEBUG -   ├─  Domain := michaelsasser.org
2020-04-30 07:25:58 - DEBUG -   ├─  Token := **HIDDEN (Length=284)**
2020-04-30 07:25:58 - DEBUG -   ┴
2020-04-30 07:25:58 - DEBUG - [SSH]
2020-04-30 07:25:58 - DEBUG -   ├─  Address := matrix.michaelsasser.org
2020-04-30 07:25:58 - DEBUG -   ├─  Port := 22
2020-04-30 07:25:58 - DEBUG -   ├─  User := michael
2020-04-30 07:25:58 - DEBUG -   ┴
2020-04-30 07:25:58 - DEBUG - Popen(['git', 'pull'], cwd=/home/michael/repos/playbooks/synapse/matrix-docker-ansible-deploy, universal_newlines=False, shell=None, istream=None)
Traceback (most recent call last):
  File "/usr/bin/matrixctl", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/matrixctl/application.py", line 126, in main
    return int(args.func(args))
  File "/usr/lib/python3.8/site-packages/matrixctl/update.py", line 41, in update
    git.pull()
  File "/usr/lib/python3.8/site-packages/matrixctl/handlers/git.py", line 120, in pull
    self.git.pull()
  File "/home/michael/.local/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/michael/.local/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/michael/.local/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull
  stderr: 'fatal: unable to access 'https://github.com/spantaleev/matrix-docker-ansible-deploy.git/': Could not resolve host: github.com'
```

**Comment by MichaelSasser** [comment]
Merged
